export const ErrorCodes = {
  ENTITY_ALREADY_EXISTS: 'ENTITY_ALREADY_EXISTS',
  INVALID_ENTITY_DATA: 'INVALID_ENTITY_DATA',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_VEHICLE_NOT_AVAILABLE: 'RESERVATION_VEHICLE_NOT_AVAILABLE',
  RESERVATION_HOLD_EXPIRED: 'RESERVATION_HOLD_EXPIRED',
  RESERVATION_INVALID_TRANSITION: 'RESERVATION_INVALID_TRANSITION',
  RESERVATION_CONTRACT_NOT_ACCEPTED: 'RESERVATION_CONTRACT_NOT_ACCEPTED',
  RESERVATION_FORBIDDEN: 'RESERVATION_FORBIDDEN',
  RESERVATION_OWNER_CANNOT_RESERVE: 'RESERVATION_OWNER_CANNOT_RESERVE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
